-- Generated by `npm run db:sql` from core/db/schema.js — DO NOT EDIT BY HAND.
-- Dialect: SQLite (Cloudflare D1) — one-time upgrade   Target: Run ONLY on a D1 database created before these columns existed

ALTER TABLE candidates ADD COLUMN post_preferences TEXT NOT NULL DEFAULT '[]';
-- (re-running is harmless for Postgres; D1 has no IF NOT EXISTS, so a second run errors "duplicate column name")
