-- Generated by `npm run db:sql` from core/db/schema.js — DO NOT EDIT BY HAND.
-- Dialect: SQLite (Cloudflare D1)   Target: wrangler d1 execute rank-mitra-db --remote --file=db/schema-d1.sql

CREATE TABLE IF NOT EXISTS candidates (

  id                     TEXT PRIMARY KEY,
  exam_id                TEXT NOT NULL,
  roll_number            TEXT NOT NULL,
  candidate_name_private TEXT NOT NULL,
  candidate_name_public  TEXT NOT NULL,
  email                  TEXT,
  exam_date              TEXT,
  shift_id               TEXT,
  shift_number           INTEGER NOT NULL DEFAULT 1,
  total_questions        INTEGER NOT NULL DEFAULT 200,
  attempted              INTEGER NOT NULL DEFAULT 0,
  unattempted            INTEGER NOT NULL DEFAULT 0,
  correct                INTEGER NOT NULL DEFAULT 0,
  wrong                  INTEGER NOT NULL DEFAULT 0,
  raw_score              REAL    NOT NULL DEFAULT 0,
  accuracy               REAL    NOT NULL DEFAULT 0,
  category               TEXT    NOT NULL DEFAULT 'UR',
  gender                 TEXT    NOT NULL DEFAULT 'Male',
  ex_serviceman          INTEGER NOT NULL DEFAULT 0,
  contract_status        INTEGER NOT NULL DEFAULT 0,
  qualifications         TEXT    NOT NULL DEFAULT '[]',
  post_preferences       TEXT    NOT NULL DEFAULT '[]',
  source_format          TEXT,
  parse_confidence       TEXT,
  file_name              TEXT,
  file_bytes             INTEGER NOT NULL DEFAULT 0,
  answer_pattern         TEXT,
  claim_token_hash       TEXT,
  submitted_at           TEXT,
  updated_at             TEXT

);

CREATE TABLE IF NOT EXISTS audit_logs (
  id         TEXT PRIMARY KEY,
  action     TEXT NOT NULL,
  details    TEXT,
  actor      TEXT,
  ip_hash    TEXT,
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS meta (
  k TEXT PRIMARY KEY,
  v TEXT
);

CREATE TABLE IF NOT EXISTS email_log (
  id         TEXT PRIMARY KEY,
  kind       TEXT,
  to_hash    TEXT,
  status     TEXT,
  error      TEXT,
  created_at TEXT
);


CREATE UNIQUE INDEX IF NOT EXISTS ux_candidates_exam_roll ON candidates (exam_id, roll_number);
CREATE INDEX IF NOT EXISTS ix_candidates_score  ON candidates (exam_id, raw_score DESC, submitted_at DESC);
CREATE INDEX IF NOT EXISTS ix_candidates_shift  ON candidates (exam_id, shift_number, raw_score DESC);
CREATE INDEX IF NOT EXISTS ix_candidates_cat    ON candidates (exam_id, category, raw_score DESC);
CREATE INDEX IF NOT EXISTS ix_candidates_gender ON candidates (exam_id, gender, raw_score DESC);
CREATE INDEX IF NOT EXISTS ix_candidates_updated ON candidates (updated_at);
CREATE INDEX IF NOT EXISTS ix_audit_created     ON audit_logs (created_at DESC);
