#!/usr/bin/env node
/**
 * Generates the deployable SQL files from core/db/schema.js so the schema,
 * the D1 bootstrap file and the Postgres migration can never drift apart.
 *
 *   npm run db:export-sql
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { pgSchema, sqliteSchema } from '../core/db/schema.js';

const root = path.resolve(import.meta.dirname, '..');
mkdirSync(path.join(root, 'db'), { recursive: true });

const header = (name) => `-- ${name}
-- GENERATED by scripts/export-sql.mjs — edit core/db/schema.js instead.
-- Usage:
--   Cloudflare D1 : npx wrangler d1 execute rank-mitra-db --remote --file=db/schema-d1.sql
--   Supabase/Neon : psql "$DATABASE_URL" -f db/schema-pg.sql   (or paste in the SQL editor)
`;

writeFileSync(path.join(root, 'db/schema-d1.sql'), header('D1 / SQLite schema') + '\n' + sqliteSchema().trim() + '\n');
writeFileSync(path.join(root, 'db/schema-pg.sql'), header('Postgres schema (Supabase / Neon / Render PG)') + '\n' + pgSchema().trim() + '\n');

console.log('wrote db/schema-d1.sql and db/schema-pg.sql');
