#!/usr/bin/env node
/**
 * Emits the schema as plain .sql files so they can be applied with tools that
 * have no Node runtime (psql, `wrangler d1 execute --file`, Supabase SQL editor).
 *
 *   npm run db:sql
 *
 * Sources of truth stay in core/db/schema.js — never hand-edit db/*.sql.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const { pgSchema, sqliteSchema, pgMigrations, ADDED_COLUMNS } = await import('../core/db/schema.js');

mkdirSync(path.join(root, 'db'), { recursive: true });

const banner = (dialect, target) =>
  `-- Generated by \`npm run db:sql\` from core/db/schema.js — DO NOT EDIT BY HAND.\n` +
  `-- Dialect: ${dialect}   Target: ${target}\n\n`;

const d1Upgrade =
  banner('SQLite (Cloudflare D1) — one-time upgrade', 'Run ONLY on a D1 database created before these columns existed') +
  ADDED_COLUMNS.map((c) => `ALTER TABLE candidates ADD COLUMN ${c.name} ${c.def};`).join('\n') +
  `\n-- (re-running is harmless for Postgres; D1 has no IF NOT EXISTS, so a second run errors "duplicate column name")\n`;

const files = [
  ['db/migrations-d1.sql', d1Upgrade],
  ['db/schema-d1.sql', banner('SQLite (Cloudflare D1)', 'wrangler d1 execute rank-mitra-db --remote --file=db/schema-d1.sql') + sqliteSchema().trim() + '\n'],
  ['db/schema-postgres.sql', banner('PostgreSQL 15+', 'psql "$DATABASE_URL" -f db/schema-postgres.sql  ·  Supabase SQL editor  ·  Neon') + pgSchema().trim() + '\n'],
];

for (const [rel, body] of files) {
  writeFileSync(path.join(root, rel), body, 'utf8');
  console.log(`✔ wrote ${rel} (${body.length} bytes)`);
}
